version: "3"

services:     
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="FIC-course"
    ports:
      - 27017:27017
    networks:
      - production-network

  app: 
    build:  ./back-end
    command: dockerize -wait tcp://mongodb:27017 -timout 40s
    #entrypoint: ["./.docker/entrypoint.sh"]
    container_name: apizao
    ports:
        - 3000:3000
    volumes: 
        - ./back-end:/home/node/app
    networks:
      - production-network
    depends_on: 
      - mongodb

networks: 
  production-network:
    driver: bridge
    
