version: "3"

services:     
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="FIC-course"
    ports:
      - 27017:27017
    networks:
      - production-network

  app: 
    build:  ./back-end
    container_name: fic-api
    ports:
        - 3000:3000
    command: npm run start
    networks:
      - production-network
    depends_on: 
      - mongodb

networks: 
  production-network:
    driver: bridge
    
